/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package review.sites;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author zaari
 */
public class Add_review1 extends javax.swing.JFrame {

    /**
     * Creates new form Add_review1
     */
    public Add_review1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtIdUsager = new javax.swing.JTextField();
        jTxtIdSite = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAfficher2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNote = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaComm = new javax.swing.JTextArea();
        jBtnAfficher = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jbtnAjouterCMT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jbtnRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 69, 0));
        jLabel2.setText("Ajouter une review");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-survey-45.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 69, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-identity-theft-45.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-google-code-45.png"))); // NOI18N

        jTxtIdUsager.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtIdUsager.setForeground(new java.awt.Color(255, 69, 0));
        jTxtIdUsager.setText("inserer votre ID");
        jTxtIdUsager.setBorder(null);
        jTxtIdUsager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdUsagerActionPerformed(evt);
            }
        });

        jTxtIdSite.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtIdSite.setForeground(new java.awt.Color(255, 69, 0));
        jTxtIdSite.setText("ID site");
        jTxtIdSite.setBorder(null);
        jTxtIdSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdSiteActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 69, 0));

        jSeparator3.setForeground(new java.awt.Color(255, 69, 0));

        jTableAfficher2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTableAfficher2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Désignation", "Code cat", "Pays"
            }
        ));
        jTableAfficher2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAfficher2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAfficher2);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 69, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-popular-45.png"))); // NOI18N
        jLabel5.setText("Note du site");

        jTextFieldNote.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextFieldNote.setForeground(new java.awt.Color(255, 69, 0));

        jTextAreaComm.setColumns(20);
        jTextAreaComm.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextAreaComm.setRows(5);
        jTextAreaComm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Commentaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(255, 69, 0))); // NOI18N
        jScrollPane2.setViewportView(jTextAreaComm);

        jBtnAfficher.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBtnAfficher.setForeground(new java.awt.Color(255, 69, 0));
        jBtnAfficher.setText("Afficher la table");
        jBtnAfficher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAfficherMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-inspection-35.png"))); // NOI18N

        jbtnAjouterCMT.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbtnAjouterCMT.setForeground(new java.awt.Color(255, 69, 0));
        jbtnAjouterCMT.setText("Ajouter le commentaire");
        jbtnAjouterCMT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnAjouterCMTMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 69, 0));
        jLabel7.setText("Entre 1 et 5");

        jbtnRetour.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbtnRetour.setForeground(new java.awt.Color(255, 69, 0));
        jbtnRetour.setText("Retour");
        jbtnRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnRetourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(jTxtIdUsager))
                                .addGap(247, 247, 247)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNote, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jTxtIdSite, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(461, 461, 461)
                                        .addComponent(jLabel7))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jBtnAfficher)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnAjouterCMT))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(67, 67, 67)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnRetour)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldNote, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtIdUsager, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtIdSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAfficher)
                    .addComponent(jbtnAjouterCMT))
                .addGap(18, 18, 18)
                .addComponent(jbtnRetour)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtIdUsagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdUsagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdUsagerActionPerformed

    private void jTxtIdSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdSiteActionPerformed

    private void jTableAfficher2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAfficher2MouseClicked
        ReviewSites co = new ReviewSites();
        co.connection();
        DefaultTableModel model = (DefaultTableModel)jTableAfficher2.getModel();
        int SelectedIndex = jTableAfficher2.getSelectedRow();
        jTxtIdSite.setText(model.getValueAt(SelectedIndex,0).toString());
    }//GEN-LAST:event_jTableAfficher2MouseClicked

    private void jBtnAfficherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAfficherMouseClicked
        ReviewSites co = new ReviewSites();
        co.connection();
        DefaultTableModel model = (DefaultTableModel)jTableAfficher2.getModel();
        model.setRowCount(0);
        try {
            co.stmt = co.conn.createStatement();
            co.rs = co.stmt.executeQuery("SELECT * FROM `sites`");
            while (co.rs.next()) {
                String IdSite = co.rs.getString(1);
                String DesSite = co.rs.getString(2);
                String CodeCat = co.rs.getString(3);
                String PaysSite = co.rs.getString(4);
                model.addRow(new String[]{IdSite,DesSite,CodeCat,PaysSite});
            }
        }catch (SQLException ex) {
            System.out.println("Error " + ex.getMessage());
        }
    }//GEN-LAST:event_jBtnAfficherMouseClicked

    private void jbtnAjouterCMTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAjouterCMTMouseClicked
        ReviewSites co = new ReviewSites();
        co.connection();
        int idusager =Integer. parseInt(jTxtIdUsager.getText());
        int idSite =Integer. parseInt(jTxtIdSite.getText());
        int note =Integer. parseInt(jTextFieldNote.getText());
        String comm = jTextAreaComm.getText();
        if(note<1 || note> 5 ){
            JOptionPane.showMessageDialog(null, "la note doit être entre 1 et 5 !");
        }
        try{
            co.stmt=co.conn.createStatement();
            co.stmt.executeUpdate("INSERT INTO `reviews` (`IdSite`,`IdUsager,`,`NoteSite`,`ComSite`) VALUES ('"+idSite+"','"+idusager+"','"+note+"','"+comm+"')");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jbtnAjouterCMTMouseClicked

    private void jbtnRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnRetourMouseClicked
        Menu pr=new Menu();
        pr.setVisible(true);
        pr.pack();
        pr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jbtnRetourMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_review1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_review1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_review1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_review1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_review1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAfficher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableAfficher2;
    private javax.swing.JTextArea jTextAreaComm;
    private javax.swing.JTextField jTextFieldNote;
    private javax.swing.JTextField jTxtIdSite;
    private javax.swing.JTextField jTxtIdUsager;
    private javax.swing.JButton jbtnAjouterCMT;
    private javax.swing.JButton jbtnRetour;
    // End of variables declaration//GEN-END:variables
}
