/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package review.sites;

/**
 *
 * @author zaari
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelajouter_usager = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelManager_site = new javax.swing.JLabel();
        jLabelListe_Sites = new javax.swing.JLabel();
        jLabelajouter_Review = new javax.swing.JLabel();
        jLabelListe_Review = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 69, 0));
        jLabel2.setText("Menu");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-menu-45.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 69, 0));

        jLabelajouter_usager.setBackground(new java.awt.Color(230, 230, 230));
        jLabelajouter_usager.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelajouter_usager.setForeground(new java.awt.Color(255, 69, 0));
        jLabelajouter_usager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-utilisateur-sexe-neutre-80.png"))); // NOI18N
        jLabelajouter_usager.setText("Ajouter Usager");
        jLabelajouter_usager.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        jLabelajouter_usager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelajouter_usager.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelajouter_usager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelajouter_usagerMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-inspection-35.png"))); // NOI18N

        jLabelManager_site.setBackground(new java.awt.Color(230, 230, 230));
        jLabelManager_site.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelManager_site.setForeground(new java.awt.Color(255, 69, 0));
        jLabelManager_site.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-entretien-80.png"))); // NOI18N
        jLabelManager_site.setText(" Manager Site ");
        jLabelManager_site.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        jLabelManager_site.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelManager_site.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelManager_site.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelManager_siteMouseClicked(evt);
            }
        });

        jLabelListe_Sites.setBackground(new java.awt.Color(230, 230, 230));
        jLabelListe_Sites.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelListe_Sites.setForeground(new java.awt.Color(255, 69, 0));
        jLabelListe_Sites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-faites-glisser-la-liste-vers-le-bas-80.png"))); // NOI18N
        jLabelListe_Sites.setText("Liste des Sites");
        jLabelListe_Sites.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        jLabelListe_Sites.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelListe_Sites.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelListe_Sites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelListe_SitesMouseClicked(evt);
            }
        });

        jLabelajouter_Review.setBackground(new java.awt.Color(230, 230, 230));
        jLabelajouter_Review.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelajouter_Review.setForeground(new java.awt.Color(255, 69, 0));
        jLabelajouter_Review.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-ajouter-aux-favoris-80.png"))); // NOI18N
        jLabelajouter_Review.setText("Ajouter Review");
        jLabelajouter_Review.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        jLabelajouter_Review.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelajouter_Review.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelajouter_Review.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelajouter_ReviewMouseClicked(evt);
            }
        });

        jLabelListe_Review.setBackground(new java.awt.Color(230, 230, 230));
        jLabelListe_Review.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelListe_Review.setForeground(new java.awt.Color(255, 69, 0));
        jLabelListe_Review.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-liste-80.png"))); // NOI18N
        jLabelListe_Review.setText(" Liste Reviews ");
        jLabelListe_Review.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        jLabelListe_Review.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelListe_Review.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelListe_Review.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelListe_ReviewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelajouter_usager)
                        .addGap(37, 37, 37)
                        .addComponent(jLabelManager_site)
                        .addGap(35, 35, 35)
                        .addComponent(jLabelListe_Sites))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabelajouter_Review)
                        .addGap(45, 45, 45)
                        .addComponent(jLabelListe_Review)))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelajouter_usager)
                    .addComponent(jLabelManager_site)
                    .addComponent(jLabelListe_Sites))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelajouter_Review)
                    .addComponent(jLabelListe_Review))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelajouter_usagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelajouter_usagerMouseClicked
        ajouter_usager pr=new ajouter_usager();
        pr.setVisible(true);
        pr.pack();
        pr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabelajouter_usagerMouseClicked

    private void jLabelManager_siteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelManager_siteMouseClicked
        Manage_site pr=new Manage_site();
        pr.setVisible(true);
        pr.pack();
        pr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabelManager_siteMouseClicked

    private void jLabelListe_SitesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelListe_SitesMouseClicked
        List_sites pr=new List_sites();
        pr.setVisible(true);
        pr.pack();
        pr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabelListe_SitesMouseClicked

    private void jLabelajouter_ReviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelajouter_ReviewMouseClicked
        Add_review1 pr=new Add_review1();
        pr.setVisible(true);
        pr.pack();
        pr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabelajouter_ReviewMouseClicked

    private void jLabelListe_ReviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelListe_ReviewMouseClicked
        List_reviews pr=new List_reviews();
        pr.setVisible(true);
        pr.pack();
        pr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabelListe_ReviewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelListe_Review;
    private javax.swing.JLabel jLabelListe_Sites;
    private javax.swing.JLabel jLabelManager_site;
    private javax.swing.JLabel jLabelajouter_Review;
    private javax.swing.JLabel jLabelajouter_usager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
