/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package review.sites;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zaari
 */
public class Supprimer_site extends javax.swing.JFrame {

    /**
     * Creates new form Supprimer_site
     */
    public Supprimer_site() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jBtnannuler2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTxtid3 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablesupprimer = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jBtnretour2 = new javax.swing.JButton();
        jBtnafficher2 = new javax.swing.JButton();
        jBtnsupprimer2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-inspection-35.png"))); // NOI18N

        jLabel11.setBackground(new java.awt.Color(230, 230, 230));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 69, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-supprimer-80.png"))); // NOI18N
        jLabel11.setText("Supprimer un Site");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jSeparator6.setForeground(new java.awt.Color(255, 69, 0));

        jBtnannuler2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jBtnannuler2.setForeground(new java.awt.Color(255, 69, 0));
        jBtnannuler2.setText("Annuler");
        jBtnannuler2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnannuler2MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review/sites/logos/icons8-chercher-45.png"))); // NOI18N

        jTxtid3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTxtid3.setForeground(new java.awt.Color(255, 69, 0));
        jTxtid3.setText("Inserer l'ID du Site à Supprimer");
        jTxtid3.setBorder(null);
        jTxtid3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtid3ActionPerformed(evt);
            }
        });

        jSeparator8.setForeground(new java.awt.Color(255, 69, 0));

        jTablesupprimer.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTablesupprimer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Désignation", "Code cat", "Pays", "Lien URL", "Handicap friendly"
            }
        ));
        jTablesupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablesupprimerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablesupprimer);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 69, 0));
        jLabel14.setText("Sinon Chercher le site à Supprimer");

        jBtnretour2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jBtnretour2.setForeground(new java.awt.Color(255, 69, 0));
        jBtnretour2.setText("Retour");
        jBtnretour2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnretour2MouseClicked(evt);
            }
        });

        jBtnafficher2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jBtnafficher2.setForeground(new java.awt.Color(255, 69, 0));
        jBtnafficher2.setText("Afficher");
        jBtnafficher2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnafficher2MouseClicked(evt);
            }
        });

        jBtnsupprimer2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jBtnsupprimer2.setForeground(new java.awt.Color(255, 69, 0));
        jBtnsupprimer2.setText("Supprimer");
        jBtnsupprimer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnsupprimer2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTxtid3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                            .addComponent(jSeparator8))))
                                .addGap(270, 270, 270))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnafficher2)
                                .addGap(86, 86, 86))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jBtnretour2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnsupprimer2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jBtnannuler2))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTxtid3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jBtnafficher2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnannuler2)
                        .addComponent(jBtnsupprimer2))
                    .addComponent(jBtnretour2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtid3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtid3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtid3ActionPerformed

    private void jBtnretour2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnretour2MouseClicked
        Manage_site pr=new Manage_site();
        pr.setVisible(true);
        pr.pack();
        pr.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBtnretour2MouseClicked

    private void jBtnafficher2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnafficher2MouseClicked
        ReviewSites co = new ReviewSites();
        co.connection();
        DefaultTableModel model = (DefaultTableModel)jTablesupprimer.getModel();
        model.setRowCount(0);
        try {
            co.stmt = co.conn.createStatement();
            co.rs = co.stmt.executeQuery("SELECT * FROM `sites`");
            while (co.rs.next()) {
                String Id = String.valueOf(co.rs.getInt(1));
                String Description = co.rs.getString(2);
                String Code = String.valueOf(co.rs.getInt(3));
                String Pays = co.rs.getString(4);
                String Lien = co.rs.getString(5);
                String Hand = String.valueOf(co.rs.getInt(6));
               
                model.addRow(new String[]{Id,Description,Code,Pays,Lien,Hand});
                
            }
        }catch (SQLException ex) {
            System.out.println("Error " + ex.getMessage());
    }//GEN-LAST:event_jBtnafficher2MouseClicked
    }
    private void jTablesupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablesupprimerMouseClicked
        ReviewSites co = new ReviewSites();
        co.connection();
        DefaultTableModel model = (DefaultTableModel)jTablesupprimer.getModel();
        int SelectedIndex = jTablesupprimer.getSelectedRow();

        jTxtid3.setText(model.getValueAt(SelectedIndex,0).toString());
    }//GEN-LAST:event_jTablesupprimerMouseClicked

    private void jBtnannuler2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnannuler2MouseClicked
        jTxtid3.setText("");
    }//GEN-LAST:event_jBtnannuler2MouseClicked

    private void jBtnsupprimer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnsupprimer2MouseClicked
        ReviewSites co = new ReviewSites();
        co.connection();
        int Id=Integer. parseInt(jTxtid3.getText());
        try{
            co.stmt=co.conn.createStatement();
            co.stmt.executeUpdate("DELETE FROM `sites` WHERE `IdSite`='"+Id+"'");
        }catch(SQLException ex){
            System.out.println("Error ! " + ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnsupprimer2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supprimer_site.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supprimer_site.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supprimer_site.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supprimer_site.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supprimer_site().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnafficher2;
    private javax.swing.JButton jBtnannuler2;
    private javax.swing.JButton jBtnretour2;
    private javax.swing.JButton jBtnsupprimer2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTablesupprimer;
    private javax.swing.JTextField jTxtid3;
    // End of variables declaration//GEN-END:variables
}
